### ISSUE TITLE
values between 1 and 101???

### ISSUE THREAD

**Issue by indus** [wdhdev/EasyScript#14]
This gives values between 1 and 101:
https://github.com/EasyScriptJS/EasyScript/blob/main/src/modules/random.js#L9

Seems a bit odd to me...

**Comment by wdhdev** [comment]
> This gives values between 1 and 101: https://github.com/EasyScriptJS/EasyScript/blob/main/src/modules/random.js#L9
> 
> Seems a bit odd to me...

This is because if it is between 1 & 100 the highest value that it will generate is 99. So if I wanted to include 100 as well it'll require to add an extra 1.

**Comment by indus** [comment]
Oh - you are right. Math.random() generates 0 to 1 exclusive(!). Always thought about it just 0 to 1 inclusive (!).
