### ISSUE TITLE
module.exports.coinflip == coinflip.js.org

### ISSUE THREAD

**Issue by indus** [wdhdev/EasyScript#16]
You may have heard about https://coinflip.js.org/ ;-)
you may use that for EasyScripts `coinflip`

**Comment by wdhdev** [comment]
> You may have heard about https://coinflip.js.org/ ;-) you may use that for EasyScripts `coinflip`

I'm the owner of the other one, haha. I deprecated CoinflipJS and incorporated it into Easy Script.

(Thanks for the subdomain btw)

https://github.com/williamdavidharrison/coinflipjs#deprecation
