### ISSUE TITLE
[FEATURE] Move to TypeScript

### ISSUE THREAD

**Issue by wdhdev** [wdhdev/EasyScript#28]
### Is there an existing issue for this?

- [X] I have searched for an [existing issue](https://github.com/EasyScriptJS/EasyScript/issues).

### What?

Move the project to TypeScript

### Description

Move the project from JavaScript to TypeScript.

### Why?

So we can use Types in modules, and reduce the workload.

**Comment by avalynndev** [comment]
Solved here: #34

**Comment by avalynndev** [comment]
Solved in Pull Request #44.

**Comment by avalynndev** [comment]
Solved again in #45

**Comment by fergqwertyui** [comment]
Hi, I would like to help with this project, is there anything you would like doing first?

**Comment by wdhdev** [comment]
> Hi, I would like to help with this project, is there anything you would like doing first?

Hello there, I'm not really sure at the moment, but if you have any ideas for modules, feel free to open an issue or make a PR adding it.

**Comment by wdhdev** [comment]
I will leave the project in JavaScript for now.
