### ISSUE TITLE
[FEATURE] New banner

### ISSUE THREAD

**Issue by avalynndev** [wdhdev/EasyScript#35]
### Is there an existing issue for this?

- [X] I have searched for an [existing issue](https://github.com/EasyScriptJS/EasyScript/issues).

### What?

better logo

### Description

I know you have got a good logo, but can you make it more attractive. I have created one logo, got the idea from https://www.npmjs.com/package/discord-arts.

 
![Easyscript.js](https://user-images.githubusercontent.com/100826194/212273301-6d6f56dc-751e-486f-ac6e-0c341a532cb2.png)

**Comment by wdhdev** [comment]
![easyscript_4-1](https://user-images.githubusercontent.com/87287585/212279481-4e909dbf-12ed-4dbe-8463-19c763dc9a98.png)

**Comment by wdhdev** [comment]
@avalynndev Please note, next time open an issue on https://github.com/easyscriptjs/images as that is where all of our logos, banners, etc are located instead of here.

**Comment by avalynndev** [comment]
Closing Issue
